# File: .github/workflows/jekyll.yml

name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # or 'master' or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/jekyll-build-pages@v1
        with:
          source: .  # <- make sure this matches your site root directory

      - uses: actions/upload-pages-artifact@v2
        with:
          path: './_site'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
